services:
  icc_version_update:
    build:
      context: ./icc_version_update
      dockerfile: Dockerfile-alpine
    container_name: icc_version_update
    environment:
      GITHUB_ACTOR: {ID}
      GITHUB_TOKEN: {TOKEN}
      GITHUB_REPOSITORY: {REPOSITORY-NAME}
    restart: always
