name: Build & Publish ICC Image

on:
  schedule:
    - cron: '0 0 * * *'   # 매일 자정 실행
  workflow_dispatch:       # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Latest Version
        run: |
          VER=$(curl -s http://download.iptime.co.kr/icc/icc_image.version | head -n1)
          echo "LATEST=$VER" >> $GITHUB_ENV

      - name: Download ICC Tarball
        run: |
          wget https://download.iptime.co.kr/icc/icc_image_${LATEST}.tar.gz

      - name: Load Docker Image
        run: |
          docker load -i icc_image_${LATEST}.tar.gz

      - name: Tag & Push to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/icc-docker
          # 방금 로드된 이미지의 ID를 가져와 태깅
          IMAGE_ID=$(docker images -q | head -n 1)
          docker tag $IMAGE_ID $IMAGE:${LATEST}
          docker tag $IMAGE_ID $IMAGE:latest
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE:${LATEST}
          docker push $IMAGE:latest
